# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo.xci
# IP: The module: 'data_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/Acode/Xilinx_FPGA/my_sobel/project/my_sobel.srcs/sources_1/ip/data_fifo/data_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
